### ISSUE TITLE
Logseq shadow-cljs parallel-build

### ISSUE THREAD

**Issue by Bad3r** [piyueh/pkgbuilds#3]
Hey, I noticed that you patch `shadow-cljs` to enable parallel-build. I was wondering if this would be a useful change to push upstream, but after reading the [documentation](https://shadow-cljs.github.io/docs/UsersGuide.html), I am not sure if it's needed.

> Unsupported or non-applicable Options:
>   Options that don’t have any effect at all include
>...
>   `:parallel-build` always enabled

Have you tested and noticed a change with/without the option enabled?

**Comment by piyueh** [comment]
When I first created this AUR package, without `parallel-build`, the building process was not parallelized. But I haven't paid attention to the building process for a while, so I'm not sure if it is still needed now. Did you notice a difference with and without this option?

**Comment by Bad3r** [comment]
Ran 3 tests with and without `parallel-build` specified in `shadow-cljs`. The test was conducted using the following script with zsh timing function:
```sh
#!/bin/sh

pkgdir="$HOME/tmp/logseq/"
static="$pkgdir/static"

cd $pkgdir
yarn install
yarn gulp:build

cd $static
yarn install

cd $pkgdir
clojure -P -M:cljs
yarn cljs:release-electron
```

The tests were run consecutively
| without |  with   |
| ------- | ------- |
| 384.66s | 386.97s |
| 384.88s | 385.10s |
| 384.62s | 378.82s |

The pattern shows that there is no difference between manually enabling parallel build or not.

**Comment by Bad3r** [comment]
Also, you can open `htop` and see that multiple cores are used even when the option is not explicitly declared 
![image](https://user-images.githubusercontent.com/25513724/208522619-45d1760a-c8c3-445b-af40-eef339389916.png)

**Comment by piyueh** [comment]
It seems the parallel build is on by default. We can remove it then

**Comment by Bad3r** [comment]
I agree, Whenever you get a chance. I can make a pr too if needed. 
TBH, I don't think it makes any difference, but it's better to keep the pkgbuild simple to review.

**Comment by piyueh** [comment]
Yes, you're welcome to make a PR anytime.

Or, if you would like, I can add you to the maintainer list of [`logseq-desktop-git`](https://aur.archlinux.org/packages/logseq-desktop-git) on AUR. Then, you can push changes directly to AUR (this GitHub repo is just a mirror). If you would like to make changes to AUR directly, I need your username on AUR.

However, for [`logseq-desktop`](https://aur.archlinux.org/packages/logseq-desktop), I am just a co-maintainer and cannot add other people. So either you need to request permission from the main maintainer of `logseq-desktop`, or you can make a PR here on GitHub, and I can push it to AUR for you.

**Comment by Bad3r** [comment]
my AUR username is `Bader`. Adding me as co-maintainer would be great. I am also a collaborator on the logseq repo and a forum/discord mod.

for managing the pkgbuild I like using GitHub to keep track of changes and I haven't really maintained a package before, so I have some reading to do first 
https://aur.archlinux.org/account/bader

**Comment by piyueh** [comment]
Great! I've added you to the maintainer list of `logseq-desktop-git`. AUR is basically another remote Git repository host. The simplest way is to clone the repo from AUR (each package is a repo on AUR), make commits, and then push back (and also push to GitHub if you want a backup/mirror). To make things more complicated and fun, you can use git's subtree/submodule to manage multiple packages in one single repo. I personally use [`aurpublish`](https://github.com/eli-schwartz/aurpublish) to mirror AUR packages as sub-repos in this GitHub repo. I believe there are other similar tools.

**Comment by Bad3r** [comment]
Awesome thanks will check it out
